Add opToDefaultMode(I)I instead of opToDefaultMode(IZ)I Error msg: java.lang.NoSuchMethodError: No static method opToDefaultMode(I)I in class Landroid/app/AppOpsManager